### ISSUE TITLE
双卡双待相关

### ISSUE THREAD

**Issue by Maskbugzero** [kuretru/SingleNet-Robot#1]
双卡双待手机能否正确选择发送短信的SIM卡？个人测试发现无论怎么互换卡槽，发送短信的都是另外一个SIM卡。

**Comment by kuretru** [comment]
闪讯机器人使用Android系统默认的短信发送卡发送短信，因此互换卡槽可能无法改变系统中的此设定。新版本增加手动指定SIM卡槽功能，待晚些时候测试完成后发布。

**Comment by Maskbugzero** [comment]
好，谢谢，感谢大佬回复。

**Comment by kuretru** [comment]
感谢使用，新版本已发布
