### ISSUE TITLE
更新时间的问题。

### ISSUE THREAD

**Issue by single-coper** [kuretru/SingleNet-Robot#2]
作者：你好，通过你的教程及软件我已经实现了上述功能，但是我们这里的密码更新时间是不固定的，请问定时发送信息的功能，能否做成采集短信内提示的密码更新时间，并按时更新。本人有这个想法，但无奈是代码小白，只能在此留言了。

**Comment by kuretru** [comment]
请提供下短信的样本

**Comment by single-coper** [comment]
尊敬的闪讯用户，您的宽带上网密码是：108939,密码在2021-05-22 15:18:42以前有效



刚看到邮件，非常感谢你能回复。👍👍👍

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by kuretru** [comment]
已新增：设置定时间隔功能，可以根据自己的需要调整定时任务的间隔。
