### ISSUE TITLE
请看详情描述

### ISSUE THREAD

**Issue by single-coper** [kuretru/SingleNet-Robot#3]
作者你好，又是我，上次更新软件之后，可以做到定时发短信了。但有个小bug。问题描述：-------------------设我昨天中午12点更新了密码，密码有效期为28小时，那么理论上今天下午4.00（28h后）密码会过期。但是我们这不会在密码到期后立刻断网。而是在今天下午10：00（第34h后）断网。  于是我想设置定时在28h 和34h之间 ，然后出现如下问题，------我设置在第30h后更新密码。密码能更新到路由器上。但是仅仅是更新上去了，他没有用新密码进行拨号。此时还没有断网是因为之前的旧密码拨号还能用一段时间，但是之前的密码拨号到第34h后会断掉。   而这个新密码没有拨上去。导致每次仍然会断网，需要再进路由器点一下“连接”才行。  -----不知道我的描述是否清晰。  最后还是谢谢作者大大，这已经让我方便很多了。

**Comment by kuretru** [comment]
这个问题有一个解决办法，就是设置一个定时任务，在每天的某一时刻，例如每天的6点，强制重新联网
`2 6 * * * /sbin/ifdown wan && /sbin/ifup wan`
另外你说的问题，可能确实存在，排查中

**Comment by single-coper** [comment]
但是如果设置更新时间为30小时，您说的每天六点重新联网，几天后”重新联网“还是会跟密码更新错开。然后还是需要手动拨号。

**Comment by kuretru** [comment]
我不知道你们学校晚上会不会断网，如果会断网，那么

> 几天后”重新联网“还是会跟密码更新错开

这个问题是始终无法避免的，除非你的手机一直连接着路由器的Wi-Fi。

每天定时重新联网，且把更新间隔设置成28小时，这个操作是为了尽可能减少断网的窗口期，让你在寝室之外的时候也可以更新密码。

另外请测试：当

> 需要手动拨号

时，使用“手动更新用户名及密码”功能，能否自动重新联网

**Comment by single-coper** [comment]
我这里24h不断网，手机24h连在wifi上，仅作闪讯拨号用。所以想--如果设置第30h自动发短信（此时上一次密码虽然到期了，但是网络没有立刻断掉），更新密码并成功用新密码连上网，那就能做到“永远不断网的效果了”  上次回复描述的：“需要手动拨号”的意思是，密码能在路由器上更新。但是需要手动点一下“保持＆应用”按钮。-------所以我对bug的理解是 密码更新到路由器了，但是路由器没有“保存＆应用”。  可能我之前描述得不够清晰，导致您没有理解我的意思。如果不能修复的话也没事的。我可以用3.2版本   。或者到期再手动点一下““保存＆应用””

**Comment by kuretru** [comment]
你用的是LuciRPC方式还是RESTful方式？LuciRPC方式问题复现不出来

**Comment by single-coper** [comment]
…………说实话，我不知道LuciRPC，RESTful是什么意思。。。。

**Comment by single-coper** [comment]
我安装的是luci-mod-rpc   然后我只安装了python3.x的那个文件（2.x没有安装，不知道只安装一个是否有影响）。之前又忘记！！！！！！设置tcp8079的端口！！！！！！。可能是这方面的问题吗？我又把路由器重置，把教程完整地走一遍，再观察观察v。可能是我自己的问题，很抱歉。…………

**Comment by kuretru** [comment]
没必要，两者装一个就可以了，luci-mod-rpc用的就是LuciRPC模式，python3.x用的是RESTful，用的哪个模式，看你客户端是如何配置的。

**Comment by single-coper** [comment]
作者你好，我听了你的建议，设置为每天早上5.00重启，现在已经完美解决之前的问题了。现在可以做到：无感更新密码≈24×7不断网了。非常感谢。有空你把这个issue关了吧。谢谢谢谢谢谢谢谢谢。！！！
