### ISSUE TITLE
Json反序列化失败

### ISSUE THREAD

**Issue by uselessbug** [kuretru/SingleNet-Robot#4]
Json反序列化失败[Unrecognized token 'No': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"No page is registered at '/rpc/auth'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file."; line: 1, column: 3]]：No page is registered at '/rpc/auth'.

**Comment by kuretru** [comment]
没有安装`luci-mod-rpc`包。
