### ISSUE TITLE
如果是未加密的PPPoE 拨号 就无法成功换密码吗

### ISSUE THREAD

**Issue by ssassassaassa** [kuretru/SingleNet-Robot#5]

**Comment by kuretru** [comment]
没明白**未加密的PPPoE 拨号**是什么意思

**Comment by ssassassaassa** [comment]
> 没明白**未加密的PPPoE 拨号**是什么意思

就是没有闪讯算法加密过的。 就只是单纯的PPPoE 拨号。浙江的都是PPPoE 拨号 任何一个路由器不需要加插件都可以拨号

**Comment by kuretru** [comment]
理论上适用于任何情况
